# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
import std/unittest
import std/options
import std/strutils # round-trip diff debug.
import std/tables # setRoleDedup table.
import UniColor

let red = color(tagSrgb, 0.80'f32, 0.20'f32, 0.20'f32).get
let blue = color(tagSrgb, 0.20'f32, 0.30'f32, 0.80'f32).get

test "import module compiles and is reachable":
  check importModule == "0.1.0"

suite "sniff — format auto-detection":
  test "UniColor header is authoritative":
    let h = genHeader("css") # "Generated by UniColor ... | format: css | ..."
    check sniffFormat(h) == some("css")
  test "malformed header (empty format token) falls through":
    # "UniColor" + "format: " present but no token char after -> structural.
    let s = "UniColor format: | nothing else here"
    check sniffFormat(s).isNone
  test "structural markers, fixed priority":
    check sniffFormat("{\"schemaVersion\":\"0\"}") == some("json")
    check sniffFormat("schemaVersion = \"0\"\n[primitives]") == some("toml")
    check sniffFormat("schemaVersion: 0\nprimitives: []") == some("yaml")
    check sniffFormat("scheme: x\nbase00: \"#000000\"") == some("base16")
    check sniffFormat("colors:\n  primary: {}") == some("alacritty")
  test "priority: json wins over base16 when both match":
    let s = "{\"schemaVersion\":\"0\",\"scheme\":\"x\",\"base00\":\"#000\"}"
    check sniffFormat(s) == some("json")
  test "no marker -> none":
    check sniffFormat("just some random text").isNone

suite "schema — migration gate + engine":
  test "migrateData is identity at the current frontier":
    let r = migrateData("0", "payload")
    check r.isOk
    check r.get == "payload"
  test "migrateData gates obsolete / future / malformed":
    check migrateData("-1", "x").error.kind == ImportFailed
    check migrateData("1", "x").error.kind == ImportFailed
    check migrateData("abc", "x").error.kind == ImportFailed
  test "applyMigrations identity when from == target":
    let r = applyMigrations("0", "0", "data")
    check r.isOk and r.get == "data"
  test "applyMigrations walks a registered chain":
    # Synthetic chain "5" -> "6" -> "7" (independent of the real frontier).
    discard registerMigration(Migration(fromVersion: "5", toVersion: "6",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d & "+6")))
    discard registerMigration(Migration(fromVersion: "6", toVersion: "7",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d & "+7")))
    let r = applyMigrations("5", "7", "d")
    check r.isOk
    check r.get == "d+6+7"
  test "applyMigrations missing step -> ImportFailed":
    check applyMigrations("5", "8", "d").error.kind == ImportFailed # no 7->8.
  test "applyMigrations step failure propagates":
    discard registerMigration(Migration(fromVersion: "8", toVersion: "9",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      err[string, ColorError](colorError(ImportFailed, "boom", "test"))))
    check applyMigrations("8", "9", "d").error.kind == ImportFailed
  test "registerMigration idempotent + rejects bad":
    check not registerMigration(Migration(fromVersion: "5", toVersion: "6",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d))) # duplicate from "5".
    check not registerMigration(Migration(fromVersion: "", toVersion: "x",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d))) # empty from.
    check not registerMigration(Migration(fromVersion: "bad", toVersion: "x",
        apply: nil)) # nil apply.
  test "applyMigrations cycle -> ImportFailed (bound guard)":
    # A registered 'toVersion' that revisits a prior version cycles 20 <-> 21
    # forever; target "30" is unreachable. The bound guard (registry size + 1)
    # catches it instead of looping.
    discard registerMigration(Migration(fromVersion: "20", toVersion: "21",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d & "+21")))
    discard registerMigration(Migration(fromVersion: "21", toVersion: "20",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d & "+20")))
    check applyMigrations("20", "30", "d").error.kind == ImportFailed
  test "sealMigrations blocks further registration":
    sealMigrations()
    check not registerMigration(Migration(fromVersion: "100",
        toVersion: "101", apply: proc(d: string): Result[string,
            ColorError] {.raises: [].} = ok[string, ColorError](d)))

suite "reconstruct — decide + assemble":
  test "decideKind: roles -> Theme, flat -> Palette, roles win":
    var i = defaultReconstructInput()
    check decideKind(i) == ikPalette # bare default has nothing -> Palette.
    i.primitives = @[ThemeToken(name: "a", color: red)]
    check decideKind(i) == ikTheme
    i.bareColors = @[red, blue]
    check decideKind(i) == ikTheme # roles win over flat.
  test "reconstruct Theme path":
    var i = defaultReconstructInput()
    i.primitives = @[ThemeToken(name: "a", color: red),
                    ThemeToken(name: "b", color: blue)]
    let r = reconstruct(i)
    check r.isOk
    check r.get.kind == ikTheme
    check r.get.theme.count == 2
  test "reconstruct Palette path":
    var i = defaultReconstructInput()
    i.bareColors = @[red, blue]
    let r = reconstruct(i)
    check r.isOk
    check r.get.kind == ikPalette
    check colors(r.get.palette).len == 2
  test "reconstruct empty source -> InvalidOp":
    let i = defaultReconstructInput()
    check reconstruct(i).error.kind == InvalidOp
  test "reconstruct propagates constructor errors (duplicate role)":
    var i = defaultReconstructInput()
    i.primitives = @[ThemeToken(name: "a", color: red),
                    ThemeToken(name: "a", color: blue)]
    check reconstruct(i).error.kind == InvalidOp

suite "partial — readColorOrSkip + setRoleDedup":
  test "readColorOrSkip ok -> some":
    var coll = PartialCollector()
    let okR = color(tagSrgb, 1.0'f32, 0.0'f32, 0.0'f32)
    let r = readColorOrSkip(okR, "a", "test", defaultImportOpts(), coll)
    check r.isOk and r.get.isSome
    check coll.warnings.len == 0
  test "readColorOrSkip err best-effort -> none + warnInvalidToken":
    var coll = PartialCollector()
    let errR = err[Color, ColorError](colorError(InvalidColor, "bad hex",
        "test"))
    let r = readColorOrSkip(errR, "a", "test", defaultImportOpts(), coll)
    check r.isOk and r.get.isNone
    check coll.warnings.len == 1
    check coll.warnings[0].code == warnInvalidToken
  test "readColorOrSkip err strict -> err":
    var coll = PartialCollector()
    let errR = err[Color, ColorError](colorError(InvalidColor, "bad hex",
        "test"))
    let r = readColorOrSkip(errR, "a", "test", ImportOpts(strict: true), coll)
    check r.isErr
    check coll.warnings.len == 0 # no warning collected on the fatal path.
  test "setRoleDedup: new + same-color re-set -> no warn":
    var tab: Table[string, Color]
    var coll = PartialCollector()
    setRoleDedup(tab, "a", red, "test", coll)
    setRoleDedup(tab, "a", red, "test", coll) # idempotent re-set.
    check coll.warnings.len == 0
    check tab["a"] == red
  test "setRoleDedup: different-color re-set -> warnDuplicateRole + last wins":
    var tab: Table[string, Color]
    var coll = PartialCollector()
    setRoleDedup(tab, "a", red, "test", coll)
    setRoleDedup(tab, "a", blue, "test", coll) # real conflict.
    check coll.warnings.len == 1
    check coll.warnings[0].code == warnDuplicateRole
    check tab["a"] == blue # last value wins.

suite "round-trip — export -> import -> re-export is byte-identical (sRGB hex)":
  # The golden invariant every format leaf documents:
  #   exportTheme(importTheme(exportTheme(t, fmt), fmt), fmt) == exportTheme(t, fmt)
  # Run with `legacySrgb: true` so every format emits sRGB hex (the slot formats
  # are sRGB-only; the data/css formats honor the flag) -> hex round-trips
  # byte-identically through parseColor + gamutMap(sRGB -> sRGB identity). Runs
  # BEFORE the registry-sealing suite below (which mutates + seals LAST).
  let rtTheme = theme([
    ThemeToken(name: "background", color: red),
    ThemeToken(name: "text.primary", color: blue),
    ThemeToken(name: "text.secondary", color: red),
    ThemeToken(name: "text.disabled", color: blue),
    ThemeToken(name: "surface", color: blue),
    ThemeToken(name: "surface.variant", color: red),
    ThemeToken(name: "overlay", color: blue),
    ThemeToken(name: "primary", color: blue),
    ThemeToken(name: "secondary", color: red),
    ThemeToken(name: "tertiary", color: blue),
    ThemeToken(name: "accent", color: red),
    ThemeToken(name: "error", color: red),
    ThemeToken(name: "warning", color: blue),
    ThemeToken(name: "success", color: blue),
    ThemeToken(name: "info", color: red),
    ThemeToken(name: "syntax.variable", color: red),
    ThemeToken(name: "syntax.constant", color: blue),
    ThemeToken(name: "syntax.type", color: red),
    ThemeToken(name: "syntax.string", color: blue),
    ThemeToken(name: "syntax.operator", color: red),
    ThemeToken(name: "syntax.keyword", color: blue),
    ThemeToken(name: "syntax.comment", color: red),
    ThemeToken(name: "syntax.function", color: blue),
    ThemeToken(name: "syntax.number", color: red),
    ThemeToken(name: "syntax.namespace", color: blue)
  ], [
    ThemeToken(name: "text.muted", alias: "text.secondary")
  ], []).get
  var sopts = defaultExportOpts()
  sopts.legacySrgb = true # sRGB hex round-trip (keep the real `--` prefix default).
  proc rt(fmt: string) =
    let out1 = exportTheme(rtTheme, fmt, sopts).get
    let imp = importTheme(out1, fmt)
    check imp.isOk
    let out2 = exportTheme(imp.get, fmt, sopts).get
    check out1 == out2
  # CSS vars FLATTENS the alias layer (a semantic role becomes a primitive on
  # import -> the sorted `orderedRoles` output reorders), so the byte-identical
  # invariant does NOT hold for css (documented in import/formats_css). The
  # role->color MAPPING is preserved (color-level round-trip): extract the
  # `--role: value;` pairs from both outputs and compare.
  proc cssVarMap(output: string): Table[string, string] =
    for line in output.splitLines():
      let s = line.strip()
      if not s.startsWith("--"):
        continue
      let sep = s.find(": ")
      if sep < 0:
        continue
      let role = s[2 ..< sep]
      let rest = s[sep + 2 ..< s.len]
      let semi = rest.find(';')
      result[role] = if semi >= 0: rest[0 ..< semi] else: rest
  test "lossless data: json / toml / yaml (full tree + alias)":
    rt("json")
    rt("toml")
    rt("yaml")
  test "flattened: css (light :root, no dark variant) — mapping-equal":
    let out1 = exportTheme(rtTheme, "css", sopts).get
    let imp = importTheme(out1, "css")
    check imp.isOk
    let out2 = exportTheme(imp.get, "css", sopts).get
    check cssVarMap(out1) == cssVarMap(out2)
  test "slot-bounded: base16 / base24":
    rt("base16")
    rt("base24")
  test "terminals: alacritty / kitty / windowsterminal / foot":
    rt("alacritty")
    rt("kitty")
    rt("windowsterminal")
    rt("foot")
  test "alacritty: cursor.text does not override primary.foreground":
    # The export emits cursor.text as a copy of fg for round-trip fidelity, but
    # a third-party config may diverge. tp.fg must stay sourced only from
    # primary.foreground. cursor.cursor is omitted here so the aux cursor->text
    # .primary map does not shadow the foreground assertion.
    let src = "colors:\n  primary:\n    background: '#000000'\n" &
        "    foreground: '#aaaaaa'\n  cursor:\n    text: '#bbbbbb'\n"
    let t = importTheme(src, "alacritty").get
    check t.prims.hasKey("text.primary")
    check t.prims["text.primary"] == parseColor("#aaaaaa").get
  test "ide (lossless slot subset): vscode / helix":
    rt("vscode")
    rt("helix")
  test "data import reconstructs the alias layer (not just primitives)":
    # The data formats preserve the semantic alias target name; the imported
    # Theme carries text.muted as a semantic alias of text.secondary, not a
    # flattened primitive.
    let out1 = exportTheme(rtTheme, "json", sopts).get
    let t = importTheme(out1, "json").get
    check t.sems.hasKey("text.muted")
    check t.sems["text.muted"] == "text.secondary"

suite "importer registry (idempotent, sealable)":
  # Mutates the global registry (registers custom importers, then seals) so it
  # runs LAST. Format leaves (when added) self-register at import time, before
  # any test runs.
  test "unknown importer -> UnknownImporter":
    check importReported("x", "definitelyNotAFormat").error.kind ==
        UnknownImporter
    check importTheme("x", "definitelyNotAFormat").error.kind ==
        UnknownImporter
    check importPalette("x", "definitelyNotAFormat").error.kind ==
        UnknownImporter
  test "defaultImportOpts is best-effort":
    check defaultImportOpts().strict == false
  test "register + dispatch + kind mismatch":
    let before = importerCount()
    let themeImp = Importer(name: "uc-test-theme",
        parse: proc(input: string, opts: ImportOpts): Result[ImportReport,
            ColorError] {.raises: [].} =
      let t = theme([ThemeToken(name: "a", color: red)], [], []).get
      ok[ImportReport, ColorError](ImportReport(
          target: ImportTarget(kind: ikTheme, theme: t),
          formatName: "uc-test-theme", schemaVersion: "0", warnings: @[])))
    let palImp = Importer(name: "uc-test-pal",
        parse: proc(input: string, opts: ImportOpts): Result[ImportReport,
            ColorError] {.raises: [].} =
      let p = palette(palUnordered, [red, blue], intentQualitative, 0).get
      ok[ImportReport, ColorError](ImportReport(
          target: ImportTarget(kind: ikPalette, palette: p),
          formatName: "uc-test-pal", schemaVersion: "0", warnings: @[])))
    check registerImporter(themeImp)
    check registerImporter(palImp)
    check importerCount() == before + 2
    # Duplicate rejected.
    check not registerImporter(themeImp)
    # Empty name / nil parse rejected.
    check not registerImporter(Importer(name: "", parse: themeImp.parse))
    check not registerImporter(Importer(name: "uc-test-nil", parse: nil))
    # Dispatch + kind mismatch.
    check importTheme("x", "uc-test-theme").isOk
    check importPalette("x", "uc-test-theme").error.kind == InvalidOp
    check importPalette("x", "uc-test-pal").isOk
    check importTheme("x", "uc-test-pal").error.kind == InvalidOp
    let rep = importReported("x", "uc-test-theme").get
    check rep.formatName == "uc-test-theme"
    check rep.schemaVersion == "0"
  test "seal blocks further registration":
    sealImporters()
    check not registerImporter(Importer(name: "after-seal",
        parse: proc(input: string, opts: ImportOpts): Result[ImportReport,
            ColorError] {.raises: [].} =
      ok[ImportReport, ColorError](ImportReport(
          target: ImportTarget(kind: ikTheme,
              theme: theme([ThemeToken(name: "a", color: red)], [],
                  []).get),
          formatName: "", schemaVersion: "", warnings: @[]))))
