# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
import std/unittest
import std/options
import std/strutils # `in` / `contains` on string.
import UniColor

let blue = color(tagOklch, 0.65'f32, 0.18'f32, 250.0'f32).get
let red = color(tagSrgb, 0.80'f32, 0.20'f32, 0.20'f32).get

test "export module compiles and is reachable":
  check exportModule == "0.1.0"

test "ucExportVersion mirrors UniColorVersion (sync invariant)":
  check ucExportVersion == UniColorVersion

suite "schema frontier + read gate":
  test "frontier constants":
    check currentSchemaVersion == "0"
    check minSchemaVersion == "0"
  test "isSupportedSchema: in-range, obsolete, future, malformed":
    check isSupportedSchema("0")
    check not isSupportedSchema("-1") # below floor.
    check not isSupportedSchema("1") # above current.
    check not isSupportedSchema("abc") # malformed.
    check not isSupportedSchema("") # empty.
  test "numeric, not lexicographic":
    check not isSupportedSchema("10") # 10 > current 0 -> future.
  test "checkSchema ok returns the version":
    let r = checkSchema("0")
    check r.isOk
    check r.get == "0"
  test "checkSchema err on obsolete / future / malformed":
    check checkSchema("-1").error.kind == ImportFailed
    check checkSchema("1").error.kind == ImportFailed
    check checkSchema("abc").error.kind == ImportFailed

suite "serialize — deterministic order + gamut map":
  test "orderedRoles: primitive -> semantic -> component, name-sorted":
    let prims = [ThemeToken(name: "z", color: red),
                 ThemeToken(name: "a", color: blue)]
    let sems = [ThemeToken(name: "m", alias: "a")]
    let t = theme(prims, sems, []).get
    let roles = orderedRoles(t)
    check roles == @[("a", tlPrimitive), ("z", tlPrimitive),
        ("m", tlSemantic)]
  test "serializeTheme: prims carry own color, sems carry resolved + alias":
    let prims = [ThemeToken(name: "z", color: red),
                 ThemeToken(name: "a", color: blue)]
    let sems = [ThemeToken(name: "m", alias: "a")]
    let t = theme(prims, sems, []).get
    let s = serializeTheme(t).get
    check s.len == 3
    check s[0].role == "a" and s[0].layer == tlPrimitive and s[0].alias == ""
    check s[1].role == "z" and s[1].layer == tlPrimitive and s[1].alias == ""
    check s[2].role == "m" and s[2].layer == tlSemantic and s[2].alias == "a"
    # The semantic node resolves to its primitive's color (blue), gamut-mapped.
    check s[2].color == s[0].color
  test "serializeTheme is deterministic (same input -> identical seq)":
    let prims = [ThemeToken(name: "z", color: red),
                 ThemeToken(name: "a", color: blue)]
    let sems = [ThemeToken(name: "m", alias: "a")]
    let t = theme(prims, sems, []).get
    let s1 = serializeTheme(t).get
    let s2 = serializeTheme(t).get
    check s1 == s2
  test "serializeTheme ignores hash-table insertion order":
    # Same role set built in reverse insertion order -> same sorted output.
    let t1 = theme([ThemeToken(name: "z", color: red),
                    ThemeToken(name: "a", color: blue)], [], []).get
    let t2 = theme([ThemeToken(name: "a", color: blue),
                    ThemeToken(name: "z", color: red)], [], []).get
    check serializeTheme(t1).get == serializeTheme(t2).get
  test "genHeader: UniColor brand + format + target + schema":
    let h = genHeader("css")
    check "Generated by UniColor" in h
    check "format: css" in h
    check "target: oklch" in h
    check "schema: 0" in h
  test "genHeader reflects legacy srgb target":
    let h = genHeader("css", SerializeOpts(target: tagSrgb, legacySrgb: true))
    check "target: srgb" in h

suite "serialize — CSS formatters":
  test "formatColorCss OKLCH form":
    let s = formatColorCss(blue, false)
    check s.startsWith("oklch(")
    check s.endsWith(")")
  test "formatColorCss sRGB hex form":
    let s = formatColorCss(red, true)
    check s.startsWith("#")
    check s.len == 7 # #rrggbb, opaque.
  test "hexByte: 1.0 -> ff, 0.0 -> 00, clamps":
    check hexByte(1.0'f32) == "ff"
    check hexByte(0.0'f32) == "00"
    check hexByte(1.5'f32) == "ff" # clamp high.
    check hexByte(-0.5'f32) == "00" # clamp low.
  test "fmtF: fixed decimals":
    check fmtF(0.5'f32, 2) == "0.50"

suite "exporter registry (idempotent, sealable)":
  # Mutates the global registry (registers a custom exporter, then seals) so it
  # runs LAST. Format leaves (when added) self-register at import time, before
  # any test runs; this suite only adds a non-colliding test exporter.
  test "unknown exporter -> UnknownExporter":
    let t = theme([ThemeToken(name: "a", color: blue)], [], []).get
    check exportTheme(t, "definitelyNotAFormat").error.kind == UnknownExporter
    check exportThemeReported(t, "definitelyNotAFormat").error.kind ==
        UnknownExporter
  test "lookup miss":
    check lookupExporter("definitelyNotAFormat").isNone
  test "defaultExportOpts: OKLCH, -- prefix, no dark":
    let o = defaultExportOpts()
    check not o.legacySrgb
    check o.prefix == "--"
    check o.dark.isNone
  test "register rejects nil / empty / duplicate, accepts new":
    let before = exporterCount()
    let good = Exporter(name: "uc-test-custom",
        render: proc(theme: Theme, opts: ExportOpts): Result[ExportReport,
            ColorError] {.raises: [].} =
      ok[ExportReport, ColorError](ExportReport(output: "CUSTOM",
          warnings: @[])))
    check registerExporter(good)
    check exporterCount() == before + 1
    check lookupExporter("uc-test-custom").isSome
    # Duplicate name rejected.
    check not registerExporter(good)
    check exporterCount() == before + 1
    # Empty name and nil render rejected.
    check not registerExporter(Exporter(name: "", render: good.render))
    check not registerExporter(Exporter(name: "uc-test-nil", render: nil))
  test "registered exporter dispatches via exportTheme / exportThemeReported":
    let t = theme([ThemeToken(name: "a", color: blue)], [], []).get
    check exportTheme(t, "uc-test-custom").get == "CUSTOM"
    let rep = exportThemeReported(t, "uc-test-custom").get
    check rep.output == "CUSTOM"
    check rep.warnings.len == 0
  test "seal blocks further registration":
    sealExporters()
    check not registerExporter(Exporter(name: "after-seal",
        render: proc(theme: Theme, opts: ExportOpts): Result[ExportReport,
            ColorError] {.raises: [].} =
      ok[ExportReport, ColorError](ExportReport(output: "",
          warnings: @[]))))
