# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
import std/unittest
import std/options
import std/tables # setRoleDedup table.
import UniColor

let red = color(tagSrgb, 0.80'f32, 0.20'f32, 0.20'f32).get
let blue = color(tagSrgb, 0.20'f32, 0.30'f32, 0.80'f32).get

test "import module compiles and is reachable":
  check importModule == "0.1.0"

suite "sniff — format auto-detection":
  test "UniColor header is authoritative":
    let h = genHeader("css") # "Generated by UniColor ... | format: css | ..."
    check sniffFormat(h) == some("css")
  test "malformed header (empty format token) falls through":
    # "UniColor" + "format: " present but no token char after -> structural.
    let s = "UniColor format: | nothing else here"
    check sniffFormat(s).isNone
  test "structural markers, fixed priority":
    check sniffFormat("{\"schemaVersion\":\"0\"}") == some("json")
    check sniffFormat("schemaVersion = \"0\"\n[primitives]") == some("toml")
    check sniffFormat("schemaVersion: 0\nprimitives: []") == some("yaml")
    check sniffFormat("scheme: x\nbase00: \"#000000\"") == some("base16")
    check sniffFormat("colors:\n  primary: {}") == some("alacritty")
  test "priority: json wins over base16 when both match":
    let s = "{\"schemaVersion\":\"0\",\"scheme\":\"x\",\"base00\":\"#000\"}"
    check sniffFormat(s) == some("json")
  test "no marker -> none":
    check sniffFormat("just some random text").isNone

suite "schema — migration gate + engine":
  test "migrateData is identity at the current frontier":
    let r = migrateData("0", "payload")
    check r.isOk
    check r.get == "payload"
  test "migrateData gates obsolete / future / malformed":
    check migrateData("-1", "x").error.kind == ImportFailed
    check migrateData("1", "x").error.kind == ImportFailed
    check migrateData("abc", "x").error.kind == ImportFailed
  test "applyMigrations identity when from == target":
    let r = applyMigrations("0", "0", "data")
    check r.isOk and r.get == "data"
  test "applyMigrations walks a registered chain":
    # Synthetic chain "5" -> "6" -> "7" (independent of the real frontier).
    discard registerMigration(Migration(fromVersion: "5", toVersion: "6",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d & "+6")))
    discard registerMigration(Migration(fromVersion: "6", toVersion: "7",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d & "+7")))
    let r = applyMigrations("5", "7", "d")
    check r.isOk
    check r.get == "d+6+7"
  test "applyMigrations missing step -> ImportFailed":
    check applyMigrations("5", "8", "d").error.kind == ImportFailed # no 7->8.
  test "applyMigrations step failure propagates":
    discard registerMigration(Migration(fromVersion: "8", toVersion: "9",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      err[string, ColorError](colorError(ImportFailed, "boom", "test"))))
    check applyMigrations("8", "9", "d").error.kind == ImportFailed
  test "registerMigration idempotent + rejects bad":
    check not registerMigration(Migration(fromVersion: "5", toVersion: "6",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d))) # duplicate from "5".
    check not registerMigration(Migration(fromVersion: "", toVersion: "x",
        apply: proc(d: string): Result[string, ColorError] {.raises: [].} =
      ok[string, ColorError](d))) # empty from.
    check not registerMigration(Migration(fromVersion: "bad", toVersion: "x",
        apply: nil)) # nil apply.
  test "sealMigrations blocks further registration":
    sealMigrations()
    check not registerMigration(Migration(fromVersion: "100",
        toVersion: "101", apply: proc(d: string): Result[string,
            ColorError] {.raises: [].} = ok[string, ColorError](d)))

suite "reconstruct — decide + assemble":
  test "decideKind: roles -> Theme, flat -> Palette, roles win":
    var i = defaultReconstructInput()
    check decideKind(i) == ikPalette # bare default has nothing -> Palette.
    i.primitives = @[ThemeToken(name: "a", color: red)]
    check decideKind(i) == ikTheme
    i.bareColors = @[red, blue]
    check decideKind(i) == ikTheme # roles win over flat.
  test "reconstruct Theme path":
    var i = defaultReconstructInput()
    i.primitives = @[ThemeToken(name: "a", color: red),
                    ThemeToken(name: "b", color: blue)]
    let r = reconstruct(i)
    check r.isOk
    check r.get.kind == ikTheme
    check r.get.theme.count == 2
  test "reconstruct Palette path":
    var i = defaultReconstructInput()
    i.bareColors = @[red, blue]
    let r = reconstruct(i)
    check r.isOk
    check r.get.kind == ikPalette
    check colors(r.get.palette).len == 2
  test "reconstruct empty source -> InvalidOp":
    let i = defaultReconstructInput()
    check reconstruct(i).error.kind == InvalidOp
  test "reconstruct propagates constructor errors (duplicate role)":
    var i = defaultReconstructInput()
    i.primitives = @[ThemeToken(name: "a", color: red),
                    ThemeToken(name: "a", color: blue)]
    check reconstruct(i).error.kind == InvalidOp

suite "partial — readColorOrSkip + setRoleDedup":
  test "readColorOrSkip ok -> some":
    var coll = PartialCollector()
    let okR = color(tagSrgb, 1.0'f32, 0.0'f32, 0.0'f32)
    let r = readColorOrSkip(okR, "a", "test", defaultImportOpts(), coll)
    check r.isOk and r.get.isSome
    check coll.warnings.len == 0
  test "readColorOrSkip err best-effort -> none + warnInvalidToken":
    var coll = PartialCollector()
    let errR = err[Color, ColorError](colorError(InvalidColor, "bad hex",
        "test"))
    let r = readColorOrSkip(errR, "a", "test", defaultImportOpts(), coll)
    check r.isOk and r.get.isNone
    check coll.warnings.len == 1
    check coll.warnings[0].code == warnInvalidToken
  test "readColorOrSkip err strict -> err":
    var coll = PartialCollector()
    let errR = err[Color, ColorError](colorError(InvalidColor, "bad hex",
        "test"))
    let r = readColorOrSkip(errR, "a", "test", ImportOpts(strict: true), coll)
    check r.isErr
    check coll.warnings.len == 0 # no warning collected on the fatal path.
  test "setRoleDedup: new + same-color re-set -> no warn":
    var tab: Table[string, Color]
    var coll = PartialCollector()
    setRoleDedup(tab, "a", red, "test", coll)
    setRoleDedup(tab, "a", red, "test", coll) # idempotent re-set.
    check coll.warnings.len == 0
    check tab["a"] == red
  test "setRoleDedup: different-color re-set -> warnDuplicateRole + last wins":
    var tab: Table[string, Color]
    var coll = PartialCollector()
    setRoleDedup(tab, "a", red, "test", coll)
    setRoleDedup(tab, "a", blue, "test", coll) # real conflict.
    check coll.warnings.len == 1
    check coll.warnings[0].code == warnDuplicateRole
    check tab["a"] == blue # last value wins.

suite "importer registry (idempotent, sealable)":
  # Mutates the global registry (registers custom importers, then seals) so it
  # runs LAST. Format leaves (when added) self-register at import time, before
  # any test runs.
  test "unknown importer -> UnknownImporter":
    check importReported("x", "definitelyNotAFormat").error.kind ==
        UnknownImporter
    check importTheme("x", "definitelyNotAFormat").error.kind ==
        UnknownImporter
    check importPalette("x", "definitelyNotAFormat").error.kind ==
        UnknownImporter
  test "defaultImportOpts is best-effort":
    check defaultImportOpts().strict == false
  test "register + dispatch + kind mismatch":
    let before = importerCount()
    let themeImp = Importer(name: "uc-test-theme",
        parse: proc(input: string, opts: ImportOpts): Result[ImportReport,
            ColorError] {.raises: [].} =
      let t = theme([ThemeToken(name: "a", color: red)], [], []).get
      ok[ImportReport, ColorError](ImportReport(
          target: ImportTarget(kind: ikTheme, theme: t),
          formatName: "uc-test-theme", schemaVersion: "0", warnings: @[])))
    let palImp = Importer(name: "uc-test-pal",
        parse: proc(input: string, opts: ImportOpts): Result[ImportReport,
            ColorError] {.raises: [].} =
      let p = palette(palUnordered, [red, blue], intentQualitative, 0).get
      ok[ImportReport, ColorError](ImportReport(
          target: ImportTarget(kind: ikPalette, palette: p),
          formatName: "uc-test-pal", schemaVersion: "0", warnings: @[])))
    check registerImporter(themeImp)
    check registerImporter(palImp)
    check importerCount() == before + 2
    # Duplicate rejected.
    check not registerImporter(themeImp)
    # Empty name / nil parse rejected.
    check not registerImporter(Importer(name: "", parse: themeImp.parse))
    check not registerImporter(Importer(name: "uc-test-nil", parse: nil))
    # Dispatch + kind mismatch.
    check importTheme("x", "uc-test-theme").isOk
    check importPalette("x", "uc-test-theme").error.kind == InvalidOp
    check importPalette("x", "uc-test-pal").isOk
    check importTheme("x", "uc-test-pal").error.kind == InvalidOp
    let rep = importReported("x", "uc-test-theme").get
    check rep.formatName == "uc-test-theme"
    check rep.schemaVersion == "0"
  test "seal blocks further registration":
    sealImporters()
    check not registerImporter(Importer(name: "after-seal",
        parse: proc(input: string, opts: ImportOpts): Result[ImportReport,
            ColorError] {.raises: [].} =
      ok[ImportReport, ColorError](ImportReport(
          target: ImportTarget(kind: ikTheme,
              theme: theme([ThemeToken(name: "a", color: red)], [],
                  []).get),
          formatName: "", schemaVersion: "", warnings: @[]))))
