# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
# import/sniff — auto-detect the format name from a source string.
# `sniffFormat(input): Option[string]` is the auto-detection entry: it returns
# the detected format name (e.g. "css", "json", "base16") or `none` if no
# marker matches.
#
# PRIMARY — UniColor generation header: every UniColor export carries the
# header `Generated by UniColor <ver> | format: <name> | target: <space> |
# schema: <ver>` (css wraps it in `/* ... */`, base16/toml/yaml/nix in
# `# ...`, lua/neovim in `-- ...`, json inside the `"//":"..."` value — see
# `genHeader` in export/serialize). The header is AUTHORITATIVE: the file
# declares what it is, so a header match returns immediately and wins over
# any structural marker. Detection scans for `UniColor` (the marker guard —
# avoids a coincidental `format: ` in random text) AND `format: `, then reads
# the token after `format: ` (alnum + `-`/`_`). An empty token (malformed
# header) falls through to the structural markers.
#
# SECONDARY — structural markers (headerless third-party or a stripped
# header): a FIXED PRIORITY list (order-stable). Each entry is a pair of
# distinctive tokens; both must be present. Priority: json > toml > yaml >
# base16 > alacritty. A source matching several is resolved by the first in
# the list (deterministic, no hash-order leak).
#
# `sniffFormat` is DETECTION only — it returns a name whether or not an
# importer is registered for it. Dispatch (sniff then importReported, err
# UnknownImporter if the name is not registered) is a caller concern; here we
# only name the format. `import` is a Nim keyword -> quoted import where
# needed.
#
# Layer: import (pure string heuristics — no color/theme dependency).
import std/strutils
import std/options

# A structural marker: a format name + the two distinctive tokens both of
# which must be present in the (headerless) source. Walked in this fixed order
# = order-stable.
const structuralMarkers: seq[(string, string, string)] = @[
  ("json", "\"schemaVersion\"", "{"),
  ("toml", "schemaVersion = ", "[primitives]"),
  ("yaml", "schemaVersion:", "primitives:"),
  ("base16", "scheme:", "base00:"),
  ("alacritty", "colors:", "primary:")
]

# Read the format-name token after `format: ` — alnum + `-`/`_`. Stops at any
# other char (space, `|`, `"`, end). Returns "" if no token char follows
# (malformed header).
proc readFormatToken(s: string, start: int): string {.raises: [].} =
  result = ""
  var i = start
  while i < s.len and (s[i] in {'a'..'z', 'A'..'Z', '0'..'9', '-', '_'}):
    result.add(s[i])
    inc i

proc sniffFormat*(input: string): Option[string] {.raises: [].} =
  ## Auto-detect the format name from `input`. PRIMARY: the UniColor generation
  ## header (the file declares its format — authoritative). SECONDARY:
  ## structural markers in a fixed priority list (order-stable). `none` if no
  ## marker matches. Detection only — does not check whether an importer is
  ## registered for the name.
  # PRIMARY — UniColor header. The marker guard (`UniColor` present) avoids a
  # coincidental `format: ` in random text; the header always carries the
  # project name.
  if "UniColor" in input and "format: " in input:
    let idx = input.find("format: ")
    let tok = readFormatToken(input, idx + "format: ".len)
    if tok.len > 0:
      return some(tok)
    # empty token (malformed header) -> fall through to structural markers.
  # SECONDARY — structural markers, fixed priority (order-stable).
  for (name, tok1, tok2) in structuralMarkers:
    if tok1 in input and tok2 in input:
      return some(name)
  none(string)
